### ISSUE TITLE
Initialize Utility Token Repository

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/utilitytoken-contracts#2]
This issue is blocked by #1 

UtilityToken contracts are used in more than one repositories. 
All repositories have its own implementations, so
- Its code duplication
- It is difficult to maintain code across the repositories.

Add/Move the following contracts in this repository
- UtilityToken.sol
- UtilityTokenInterface.sol
- UtilityTokenRequiredInterface.sol

## TODOs
- [ ] Add/move the contracts
- [ ] Add/Move the unit tests for all the above contracts
- [ ] Create README (look at the openst-contracts README; link to developer-guidelines)
